### ISSUE TITLE
Duration 0 jobs are not ignored, exactly...

### ISSUE THREAD

**Issue by DerekLong101** [dwave-examples/job-shop-scheduling-cqm#7]
Although it is true that a 0 duration job takes no time to execute, in this model it does require to "touch the machine" in the sense that there must be a point on the timeline for the corresponding machine where it is not busy. 

As an example:

#Num of jobs: 3
#Num of machines: 3
                task 0            task 1            task 2
  job id    machine    dur    machine    dur    machine    dur
--------  ---------  -----  ---------  -----  ---------  -----
       0          1     10          2      0          0      0
       1          2      2          1      0          0      3
       2          2      3          1      0          0      2
[jssinstance.txt](https://github.com/dwave-examples/job-shop-scheduling-cqm/files/8079394/jssinstance.txt)

has a makespan of 14 in this model, even though it should only really need 10 if a 0 duration job is not executed. The issue is that jobs 1 and 2 both claim machine 1 for a 0 duration job, but it is occupied for job 0 for 10 time units. 

Obviously the solution is to a version of the problem in which 0 duration jobs are constrained to "see" the machine free for an instant at the time it requires it. Either the description of the problem should make that clearer, or else the solution should actually ignore duration 0 jobs (allow them to be "executed" concurrently with another job).

For example, simply add the line:

if data.task_duration[k,task_k] > 0 and data.task_duration[j,task_j] > 0 :

at job_shop_scheduler.py:91.

**Comment by mhramani** [comment]
@DerekLong101 thank you very  much for reporting this issue and also providing a solution. I created a PR to address this issue.
Thanks!
